# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b12e184a22cd54ccbf358f12c1193a6e58a6b78c70f5356cf38621cd6457325508d1dcb0e1fddf506c5d79064830985e984aad30269c6dc98ad8d830275e4e85

test:
  secret_key_base: 8cdf560a9d1846e4558782d8d1f465d45d549b656e7f2137b94d240f19a2de543b4595ffc61f3fd122146da4f654e25c0613b0ab4b0eeab5cc877d45d87e1fc9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: b12e184a22cd54ccbf358f12c1193a6e58a6b78c70f5356cf38621cd6457325508d1dcb0e1fddf506c5d79064830985e984aad30269c6dc98ad8d830275e4e85
